# Generated by Django 4.2.8 on 2023-12-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0002_worker_user1_constructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constructor',
            new_name='Contactor',
        ),
    ]
