# Generated by Django 4.2.8 on 2023-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0004_contractor_delete_contactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='img',
            field=models.ImageField(default=-2023, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
