# Generated by Django 4.2.8 on 2023-12-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0005_worker_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='ctype',
        ),
    ]
