# Generated by Django 4.2.8 on 2023-12-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0006_remove_contractor_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
