# Generated by Django 4.2.8 on 2023-12-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0007_contractor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='status',
        ),
    ]
