# Generated by Django 4.2.8 on 2023-12-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0008_remove_contractor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userworkrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype', models.CharField(max_length=100, null=True)),
                ('uphone', models.CharField(max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('req', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('payment', models.CharField(default='pending', max_length=100, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractor')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.user1')),
            ],
        ),
    ]
