# Generated by Django 4.2.8 on 2023-12-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0009_userworkrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkrequest',
            old_name='req',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userworkrequest',
            old_name='uphone',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='userworkrequest',
            old_name='uid',
            new_name='user',
        ),
    ]
