# Generated by Django 4.2.8 on 2023-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0010_rename_req_userworkrequest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkrequest',
            name='payment',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userworkrequest',
            name='status',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
