# Generated by Django 4.2.8 on 2023-12-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0012_alter_userworkrequest_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='process', max_length=10)),
                ('payments', models.CharField(default='pending', max_length=10)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractor')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.userworkrequest')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.user1')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.worker')),
            ],
        ),
    ]
