# Generated by Django 4.2.8 on 2024-01-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0014_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workerfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractor')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.user1')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.worker')),
            ],
        ),
    ]
