# Generated by Django 4.2.8 on 2024-01-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0016_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='cid',
            field=models.ForeignKey(default=-2024, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractor'),
            preserve_default=False,
        ),
    ]
