# Generated by Django 4.2.8 on 2024-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0017_customerpayment_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotedworks',
            name='amount',
            field=models.IntegerField(default=-2024),
            preserve_default=False,
        ),
    ]
