# Generated by Django 4.2.8 on 2024-01-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0019_alter_customerpayment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotedworks',
            name='amount',
        ),
    ]
