# Generated by Django 4.2.8 on 2024-01-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0020_remove_allotedworks_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(default='paid', max_length=15),
        ),
    ]
