# Generated by Django 4.2.8 on 2024-01-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0021_customerpayment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractorpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='paid', max_length=15)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.contractor')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.user1')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.worker')),
            ],
        ),
    ]
