# Generated by Django 4.2.8 on 2024-01-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0022_contractorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user1',
            name='wages',
            field=models.IntegerField(),
        ),
    ]
